### ISSUE TITLE
Implement NONBLOCKING; Fix Frame Use

### ISSUE THREAD

**Issue by kalzoo** [rigetti/quil-rust#10]
Currently, `Program::get_blocking_frames` is incomplete and incorrect in terms of determining which frames are used by an instruction.

Further, `NONBLOCKING` is not yet supported for `CAPTURE` and `RAW-CAPTURE`.

These could be fixed with one cohesive change.

**Comment by notmgsk** [comment]
@kalzoo How much of this is still to be done? It looks like `NONBLOCKING` is supported, at least during parsing, for those instructions.

**Comment by notmgsk** [comment]
There's also the commit `* Breaking: fix Program#get_blocking_frames; implement NONBLOCKING`

**Comment by kalzoo** [comment]
You're right @notmgsk , I just hadn't linked the issue correctly. This is implemented now
